workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter clean and get packages
        script: |
          flutter clean
          flutter pub get

      - name: Force iOS deployment target
        script: |
          cd ios
          sed -i '' "s/# platform :ios.*/platform :ios, '15.0'/" Podfile
          sed -i '' "s/platform :ios.*/platform :ios, '15.0'/" Podfile
          echo "---- PODFILE ----"
          head -20 Podfile
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS without codesign
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/archive/*.xcarchive
      - build/ios/iphoneos/*.app