workflows:
  ios-workflow:
    name: "iOS Build"

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        certificates:
          - ortakhesap-cert
        provisioning_profiles:
          - ortakhesap-profile

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build signed IPA
        script: |
          flutter build ipa --release --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive