workflows:
  ios-workflow:
    name: "iOS Build"

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        certificates:
          - ortakhesap-cert
        provisioning_profiles:
          - ortakhesap-profile

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install

      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Build signed IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-workflow:
    name: "Android Build"

    environment:
      flutter: stable
      android_signing:
        - Ortak_Hesap_Takip

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab

    publishing:
      google_play:
        credentials: $GPLAY_SERVICE_ACCOUNT_JSON
        track: internal
        submit_to_rollout: false