// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Afa0ABxp7zNWL4SicKlJS6RglK054Ww',
    appId: '1:159656243067:web:8d08e4bd5dddadeae9d7de',
    messagingSenderId: '159656243067',
    projectId: 'ortak-hesap-app-cd595',
    authDomain: 'ortak-hesap-app-cd595.firebaseapp.com',
    storageBucket: 'ortak-hesap-app-cd595.firebasestorage.app',
    measurementId: 'G-WG219CJ786',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh9NhuOMZyVMXsLdLmRy7BAUfP304ZpCU',
    appId: '1:159656243067:android:f5f3d69175667b55e9d7de',
    messagingSenderId: '159656243067',
    projectId: 'ortak-hesap-app-cd595',
    storageBucket: 'ortak-hesap-app-cd595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtE4CKZ09kcEJYv0Y0iJV3SjmyZ_SiqQA',
    appId: '1:159656243067:ios:7ffad5b79acd6370e9d7de',
    messagingSenderId: '159656243067',
    projectId: 'ortak-hesap-app-cd595',
    storageBucket: 'ortak-hesap-app-cd595.firebasestorage.app',
    iosBundleId: 'com.example.ortakHesap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtE4CKZ09kcEJYv0Y0iJV3SjmyZ_SiqQA',
    appId: '1:159656243067:ios:7ffad5b79acd6370e9d7de',
    messagingSenderId: '159656243067',
    projectId: 'ortak-hesap-app-cd595',
    storageBucket: 'ortak-hesap-app-cd595.firebasestorage.app',
    iosBundleId: 'com.example.ortakHesap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Afa0ABxp7zNWL4SicKlJS6RglK054Ww',
    appId: '1:159656243067:web:263af3c821209065e9d7de',
    messagingSenderId: '159656243067',
    projectId: 'ortak-hesap-app-cd595',
    authDomain: 'ortak-hesap-app-cd595.firebaseapp.com',
    storageBucket: 'ortak-hesap-app-cd595.firebasestorage.app',
    measurementId: 'G-5BCT9GMBCP',
  );
}
